version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    groups:
      angular:
        patterns:
          - "@angular*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint*"
    commit-message:
      prefix: "build"
    labels:
      - "dependabot"
      - "frontend"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    commit-message:
      prefix: "build"
    labels:
      - "dependabot"
      - "github-actions"
    open-pull-requests-limit: 20
