version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "01:00"
    commit-message:
      prefix: 'build'
    labels:
      - 'area: build & ci'
      - 'target: patch'
      - 'action: merge'
    open-pull-requests-limit: 0
