version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "01:00"
    commit-message:
      prefix: 'build'
    labels:
      - 'dependabot'
      - 'frontend'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "01:00"
    commit-message:
      prefix: 'build'
    labels:
      - 'dependabot'
      - 'github-actions'
    open-pull-requests-limit: 10
