# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Common build

on:
  push:
    branches: [ "main", "**" ]
  pull_request:
    branches: [ "main", "**" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
    - run: npm i --legacy-peer-deps
    - run: npm test
    - run: npm run build --if-present

