# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Common build

on:
  push:
    branches: [ "main", "**" ]
  pull_request:
    branches: [ "main", "**" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm i --legacy-peer-deps
    - name: Check format
      run: npm run lint
    - name: Run unit tests
      run: npm test
    - name: Do the build
      run: npm run build --if-present

